quarkus.datasource.db-kind = postgresql
quarkus.websockets-next.server.supported-subprotocols=bearer-token-carrier
quarkus.websockets-next.server.propagate-subprotocol-headers=true

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*